dist: bionic
os: linux
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - cmake
script:
  - export CC=/usr/bin/gcc-10
  - export CXX=/usr/bin/g++-10
  - mkdir build && cd build
  - cmake ..
  - make